version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 10
    labels: ["dependencies", "ci"]
    commit-message:
      prefix: "ci(actions)"
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "04:30"
      timezone: UTC
    open-pull-requests-limit: 5
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "ci(pip)"
