name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Package (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }
          - { os: windows-latest }

    steps:
      - uses: actions/checkout@v4

      - name: Install ccache (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ccache

      - name: Configure (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          cmake -S . -B build \
            -DWITH_LIBMODBUS=OFF -DWITH_TESTS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 \
            -DWITH_LIBMODBUS=OFF -DWITH_TESTS=OFF -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Package (cpack)
        shell: bash
        run: |
          set -e
          (cd build && cpack -C Release)
          echo "Generated packages:" && ls -1 build/*.zip build/*.tgz 2>/dev/null || true

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.zip
            build/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

