name: Sanitizers (Linux)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1,15 * *'  # 每月 1 日與 15 日 04:00 UTC（雙週一次）

jobs:
  asan-ubsan:
    name: ASan+UBSan (${{ matrix.build_type }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, RelWithDebInfo]
    steps:
      - uses: actions/checkout@v5

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache

      - name: Configure with sanitizers
        run: |
          SAN='-fsanitize=address,undefined -fno-omit-frame-pointer -O1 -g'
          BUILD_DIR="build-sanitizers-${{ matrix.build_type }}"
          cmake -S . -B "$BUILD_DIR" \
            -DWITH_LIBMODBUS=OFF -DWITH_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_C_FLAGS="$SAN" -DCMAKE_CXX_FLAGS="$SAN" -DCMAKE_EXE_LINKER_FLAGS="$SAN" -DCMAKE_SHARED_LINKER_FLAGS="$SAN"

      - name: Build
        run: |
          BUILD_DIR="build-sanitizers-${{ matrix.build_type }}"
          cmake --build "$BUILD_DIR" --config ${{ matrix.build_type }} --parallel

      - name: Run unit tests (sanitized)
        env:
          ASAN_OPTIONS: detect_leaks=1:abort_on_error=1
          UBSAN_OPTIONS: print_stacktrace=1
        run: |
          set -e
          BUILD_DIR="build-sanitizers-${{ matrix.build_type }}"
          ctest --test-dir "$BUILD_DIR" -R '^unit_' --output-on-failure --timeout 120 \
            || (echo 'Re-running unit tests verbosely...'; ctest --test-dir "$BUILD_DIR" -R '^unit_' -V --timeout 120; exit 1)
